package com.paulorchard.islandcraft.weatherofarrakis;

import com.hypixel.hytale.component.ResourceType;
import com.hypixel.hytale.server.core.event.events.player.PlayerReadyEvent;
import com.hypixel.hytale.server.core.plugin.JavaPlugin;
import com.hypixel.hytale.server.core.plugin.JavaPluginInit;
import com.hypixel.hytale.server.core.universe.world.storage.EntityStore;
import com.hypixel.hytale.server.core.util.Config;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.logging.Level;

public class WeatherOfArrakisPlugin extends JavaPlugin {

    private static WeatherOfArrakisPlugin instance;

    // Must be created before setup(); the server loads it from disk in between.
    private final Config<WeatherOfArrakisConfig> config =
            withConfig(WeatherOfArrakisConfig.FILE_NAME, WeatherOfArrakisConfig.CODEC);

    private ResourceType<EntityStore, CoriolisStormResource> stormResourceType;

    public WeatherOfArrakisPlugin(JavaPluginInit init) {
        super(init);
        instance = this;
    }

    public static WeatherOfArrakisPlugin get() {
        return instance;
    }

    public ResourceType<EntityStore, CoriolisStormResource> getStormResourceType() {
        return stormResourceType;
    }

    @Override
    protected void setup() {
        writeDefaultConfig();

        stormResourceType = getEntityStoreRegistry().registerResource(
                CoriolisStormResource.class, CoriolisStormResource.ID, CoriolisStormResource.CODEC);

        CoriolisStormSystem stormSystem = new CoriolisStormSystem(config::get);
        getEntityStoreRegistry().registerSystem(stormSystem);
        getCommandRegistry().registerCommand(new CoriolisCommand(stormSystem));
        getEventRegistry().registerGlobal(PlayerReadyEvent.class, stormSystem::onPlayerReady);

        getLogger().at(Level.INFO).log("Coriolis storms run in worlds generated by %s",
                Arrays.toString(config.get().getGeneratorTypes()));
    }

    /** The server reads the config file but never creates it, so write the defaults on first run. */
    private void writeDefaultConfig() {
        Path file = getDataDirectory().resolve(WeatherOfArrakisConfig.FILE_NAME + ".json");
        if (Files.exists(file)) {
            return;
        }
        try {
            Files.createDirectories(getDataDirectory());
            config.save().join();
            getLogger().at(Level.INFO).log("Wrote default config to %s", file);
        } catch (Exception e) {
            getLogger().at(Level.WARNING).withCause(e).log("Could not write default config to %s", file);
        }
    }
}
