package com.paulorchard.islandcraft.weatherofarrakis;

import com.hypixel.hytale.component.ResourceType;
import com.hypixel.hytale.server.core.asset.type.blocktype.config.BlockType;
import com.hypixel.hytale.server.core.event.events.player.PlayerReadyEvent;
import com.hypixel.hytale.server.core.plugin.JavaPlugin;
import com.hypixel.hytale.server.core.plugin.JavaPluginInit;
import com.hypixel.hytale.server.core.universe.world.storage.EntityStore;
import com.hypixel.hytale.server.core.util.Config;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.logging.Level;

public class WeatherOfArrakisPlugin extends JavaPlugin {

    private static WeatherOfArrakisPlugin instance;

    // Must be created before setup(); the server loads it from disk in between.
    private final Config<WeatherOfArrakisConfig> config =
            withConfig(WeatherOfArrakisConfig.FILE_NAME, WeatherOfArrakisConfig.CODEC);

    private ResourceType<EntityStore, CoriolisStormResource> stormResourceType;

    public WeatherOfArrakisPlugin(JavaPluginInit init) {
        super(init);
        instance = this;
    }

    public static WeatherOfArrakisPlugin get() {
        return instance;
    }

    public ResourceType<EntityStore, CoriolisStormResource> getStormResourceType() {
        return stormResourceType;
    }

    @Override
    protected void setup() {
        writeConfig();

        stormResourceType = getEntityStoreRegistry().registerResource(
                CoriolisStormResource.class, CoriolisStormResource.ID, CoriolisStormResource.CODEC);

        CoriolisStormSystem stormSystem = new CoriolisStormSystem(config::get);
        getEntityStoreRegistry().registerSystem(stormSystem);
        getEntityStoreRegistry().registerSystem(new CoriolisExposureSystem(config::get));
        getEntityStoreRegistry().registerSystem(new CoriolisBonesSystem(config::get));
        getEntityStoreRegistry().registerSystem(new CoriolisFrontSystem(config::get));
        CoriolisLightningSystem lightningSystem = new CoriolisLightningSystem(config::get);
        getEntityStoreRegistry().registerSystem(lightningSystem);
        CoriolisStorm.addPhaseListener(lightningSystem);
        CoriolisStorm.addPhaseListener((world, previous, current) -> {
            if (current == CoriolisPhase.STORM) {
                CoriolisEffects.arrivalShake(world, config.get());
            }
        });
        getCommandRegistry().registerCommand(new CoriolisCommand(stormSystem, lightningSystem));
        getEventRegistry().registerGlobal(PlayerReadyEvent.class, stormSystem::onPlayerReady);

        getLogger().at(Level.INFO).log("Coriolis storms run in worlds generated by %s",
                Arrays.toString(config.get().getGeneratorTypes()));
    }

    /** Assets are loaded by now, so say at once if one this mod relies on is missing. */
    @Override
    protected void start() {
        if (CoriolisStormDamage.cause() == null) {
            getLogger().at(Level.SEVERE).log("Damage cause '%s' is not loaded, so the storm cannot hurt anyone",
                    CoriolisStormDamage.CAUSE_ID);
        }
        String boneBlock = config.get().getBoneBlock();
        if (!boneBlock.isEmpty() && BlockType.getAssetMap().getIndex(boneBlock) == Integer.MIN_VALUE) {
            getLogger().at(Level.WARNING).log("Bone block '%s' does not exist, so no bones will be placed", boneBlock);
        }
    }

    /**
     * The server reads the config file but never creates it. Writing it back on every start
     * creates it on first run and adds any setting a newer version of the mod has introduced.
     */
    private void writeConfig() {
        Path file = getDataDirectory().resolve(WeatherOfArrakisConfig.FILE_NAME + ".json");
        try {
            Files.createDirectories(getDataDirectory());
            config.save().join();
        } catch (Exception e) {
            getLogger().at(Level.WARNING).withCause(e).log("Could not write config to %s", file);
        }
    }
}
